const category = {
  NONE: "None",
  CAKE: "Cake",
  CUPCAKE: "Cupcake",
  JAR: "Jar Cake",
};

const flavour = {
  NONE: "None",
  CHOCOLATE: "Chocolate",
  VANILLA: "Vanilla",
  STRAWBERRY: "Strawberry",
  REDVELVET: "Red Velvet",
  FRUIT: "Fruit",
  BLACKFOREST: "Black Forest",
};

const type = {
  NONE: "None",
  FONDANT: "Fondant",
  PULLUP: "Pull-Up",
  BENTO: "Bento",
  MOUSSE: "Mousse",
};

const occasion = {
  NONE: "None",
  BIRTHDAY: "Birthday",
  WEDDING: "Wedding",
  ANNIVERSARY: "Anniversary",
  CHRISTMAS: "Christmas",
  VALENTINES: "Valentine's Day",
};

/*** TEST DATA ***/

const test = {
  id: "cc_01",
  name: "Christmas Confetti",
  desc: "Chocolate Cupcake with Confetti",
  minPrice: "Rs. 200",
  discountedPrice: "Rs. 150",
  discount: "20%",
  rating: 4.5,
  ratingNo: 13,
  // images: [Christmas, Christmas2, Christmas3],
  flavour: [flavour.CHOCOLATE, flavour.VANILLA, flavour.STRAWBERRY],
  occasion: occasion.CHRISTMAS,
  category: category.CUPCAKE,
  type: type.NONE,
  sameDayDelivery: true,
  bestSeller: false,
  new: true,
  eggless: true,
  weight: ["500 gm", "1 kg"],
  priceList: [
    {
      weight: "500 gm",
      flavour: flavour.CHOCOLATE,
      price: "Rs. 400",
      discountedPrice: "Rs. 320",
      discount: "20%",
    },
    {
      weight: "1 kg",
      flavour: flavour.CHOCOLATE,
      price: "Rs. 450",
    },
    {
      weight: "500 gm",
      flavour: flavour.VANILLA,
      price: "Rs. 200",
    },
    {
      weight: "1 kg",
      flavour: flavour.VANILLA,
      price: "Rs. 250",
      discountedPrice: "Rs. 150",
      discount: "10%",
    },
    {
      weight: "500 gm",
      flavour: flavour.STRAWBERRY,
      price: "Rs. 300",
    },
    {
      weight: "1 kg",
      flavour: flavour.STRAWBERRY,
      price: "Rs. 350",
    },
  ],
  info: [
    "Our Christmas Confetti cake is the perfect dessert for your Christmas spread.",

    "This chocolate cupcake has a moist and soft base, topped with a dollop with confetti-filled buttercream.",

    "Since our cakes are baked and decorated by hand once you place your order, the actual product might differ slightly from the photos provided here.",

    "Note: Please consume within 24 hours of receiving",
  ],
  reviews: [
    {
      name: "John Travolta",
      location: "Patna, Bihar",
      date: "24/10/2021",
      // images: [Christmas3],
      weight: null,
      flavour: null,
      text: "I ordered a cupcake and danced Salsa with it.",
    },
    {
      name: "LeBron James",
      location: "Patna, Bihar",
      date: "04/09/2021",
      // images: [Christmas, Christmas2],
      weight: null,
      flavour: null,
      text: "I ordered a cupcake and dunked it into the bin.",
    },
    {
      name: "Lionel Messy",
      location: "Kolkata, West Bengal",
      date: "20/09/2021",
      images: null,
      weight: null,
      flavour: null,
      text: "I ordered a cupcake and shot it in the goal.",
    },
  ],
};
/**** CUPCAKES *****/

export const cupcakes = [
  {
    id: "cupcake_christmas_confetti",
    name: "Christmas Confetti",
    desc: "Chocolate Cupcake sprinkled with Confetti",
    minPrice: "Rs. 250",
    discountedPrice: "Rs. 200",
    discount: "20%",
    rating: 5,
    ratingNo: 1,
    images: [
      "/cupcakes/christmas.webp",
      "/cupcakes/christmas-2.webp",
      "/cupcakes/christmas-3.webp",
    ],
    flavour: [flavour.CHOCOLATE],
    occasion: occasion.CHRISTMAS,
    category: category.CUPCAKE,
    type: type.NONE,
    sameDayDelivery: true,
    bestSeller: true,
    eggless: true,
    info: [
      "Our Christmas Confetti cake is the perfect dessert for your Christmas spread.",
      "This chocolate cupcake has a moist and soft base, topped with a dollop of confetti-filled buttercream.",
      "Since our cakes are baked and decorated by hand once you place your order, the actual product might differ slightly from the photos provided here.",
      "Note: Please consume within 24 hours of receiving",
    ],
    reviews: [
      {
        name: "John Travolta",
        location: "Patna, Bihar",
        date: "Decemeber 24, 2021",
        rating: 5,
        images: ["/cupcakes/christmas.webp"],
        text: "This was the best Christmas cupcake I have ever had. It was so good that my dead neighbout came out of his grave to take a bite.",
      },
    ],
  },
  {
    id: "cupcake_classic_red_velvet",
    name: "Classic Red Velvet",
    desc: "Classic red velvet cupcake",
    minPrice: "Rs. 250",
    rating: 0,
    ratingNo: 0,
    images: [
      "/cupcakes/redvelvet.webp",
      "/cupcakes/redvelvet-2.webp",
      "/cupcakes/redvelvet-3.webp",
    ],
    flavour: [flavour.REDVELVET],
    occasion: occasion.NONE,
    category: category.CUPCAKE,
    type: type.NONE,
    sameDayDelivery: true,
    bestSeller: false,
    eggless: false,
    info: [
      "Our Classic Red Velvet cupcake is the forever-favourite red velvet cake topped with a delicious frosting, sprinkled with chocochips and confetti.",
      "Since our cakes are baked and decorated by hand once you place your order, the actual product might differ slightly from the photos provided here.",
      "Note: Please consume within 24 hours of receiving",
    ],
    reviews: [],
  },
  {
    id: "cupcake_happy_halloween",
    name: "Happy Halloween",
    desc: "Halloween-themed vanilla/chocolate cupcake",
    minPrice: "Rs. 200",
    discount: "20%",
    discountedPrice: "Rs. 160",
    rating: 0,
    ratingNo: 0,
    images: [
      "/cupcakes/halloween.webp",
      "/cupcakes/halloween-2.jpeg",
      "/cupcakes/halloween-3.webp",
    ],
    flavour: [flavour.VANILLA, flavour.CHOCOLATE],
    occasion: occasion.NONE,
    category: category.CUPCAKE,
    type: type.NONE,
    sameDayDelivery: false,
    bestSeller: false,
    eggless: true,
    priceList: [
      {
        flavour: flavour.VANILLA,
        price: "Rs. 200",
        discount: "20%",
        discountedPrice: "Rs. 160",
      },
      {
        flavour: flavour.CHOCOLATE,
        price: "Rs. 220",
        discount: "20%",
        discountedPrice: "Rs. 175",
      },
    ],
    info: [
      "Add a dash of delicious fun to your kid's halloween party with our Halloween-themed cupcakes",
      "Take your pick between Vanilla and Chocolate flavours.",
      "Since our cakes are baked and decorated by hand once you place your order, the actual product might differ slightly from the photos provided here.",
      "Note: Please consume within 24 hours of receiving",
    ],
    reviews: [],
  },
  {
    id: "cupcake_zingy_lemon",
    name: "Zingy Lemon",
    desc: "Lemon flavoured cupcake with lemon icing",
    minPrice: "Rs. 200",
    rating: 0,
    ratingNo: 0,
    images: ["/cupcakes/lemon.jpeg", "/cupcakes/lemon-2.jpeg"],
    flavour: [flavour.FRUIT],
    occasion: occasion.NONE,
    category: category.CUPCAKE,
    type: type.NONE,
    sameDayDelivery: false,
    bestSeller: false,
    eggless: true,
    info: [
      "These easy lemon cupcakes are moist, fluffy, zingy and topped with an incredible lemon buttercream that's a lemon-lover's dream!",
      "Since our cakes are baked and decorated by hand once you place your order, the actual product might differ slightly from the photos provided here.",
      "Note: Please consume within 24 hours of receiving",
    ],
    reviews: [],
  },
  {
    id: "cupcake_matcha_magic",
    name: "Matcha Magic",
    desc: "Matcha green tea flavoured cupcakes",
    minPrice: "Rs. 200",
    discount: "20%",
    discountedPrice: "Rs. 160",
    rating: 0,
    ratingNo: 0,
    images: ["/cupcakes/matcha.webp"],
    flavour: [flavour.VANILLA, flavour.CHOCOLATE],
    occasion: occasion.NONE,
    category: category.CUPCAKE,
    type: type.NONE,
    sameDayDelivery: false,
    bestSeller: false,
    eggless: false,
    priceList: [
      {
        flavour: flavour.VANILLA,
        price: "Rs. 200",
        discount: "20%",
        discountedPrice: "Rs. 160",
      },
      {
        flavour: flavour.CHOCOLATE,
        price: "Rs. 220",
        discount: "20%",
        discountedPrice: "Rs. 175",
      },
    ],
    info: [
      "Soft and fluffy Matcha Green Tea Cupcakes topped with a white cloud of vanilla whipped cream taste just like a Matcha green tea Frappuccino!",
      "Since our cakes are baked and decorated by hand once you place your order, the actual product might differ slightly from the photos provided here.",
      "Note: Please consume within 24 hours of receiving",
    ],
    reviews: [],
  },
  {
    id: "cupcake_baby_blue",
    name: "Baby Blue",
    desc: "Vanilla cupcake with teal frosting",
    minPrice: "Rs. 250",
    rating: 0,
    ratingNo: 0,
    images: ["/cupcakes/teal.webp"],
    flavour: [flavour.VANILLA],
    occasion: occasion.NONE,
    category: category.CUPCAKE,
    type: type.NONE,
    sameDayDelivery: true,
    bestSeller: false,
    eggless: false,
    info: [
      "These delicious snowy super moist chocolate cupcakes with blue buttercream frosting are here to brighten up your winter holidays!",
      "Since our cakes are baked and decorated by hand once you place your order, the actual product might differ slightly from the photos provided here.",
      "Note: Please consume within 24 hours of receiving",
    ],
    reviews: [],
  },
  {
    id: "cupcake_peachy_tropicana",
    name: "Peachy Tropicana",
    desc: "Peachy flavoured cupcakes",
    minPrice: "Rs. 200",
    discount: "20%",
    discountedPrice: "Rs. 160",
    rating: 0,
    ratingNo: 0,
    images: [
      "/cupcakes/peach.webp",
      "/cupcakes/peach-2.webp",
      "/cupcakes/peach-3.webp",
    ],
    flavour: [flavour.FRUIT],
    occasion: occasion.NONE,
    category: category.CUPCAKE,
    type: type.NONE,
    sameDayDelivery: true,
    bestSeller: false,
    eggless: true,
    info: [
      "These peach-flavoured cupcakes with soft, peachy frosting are here to satiate your fruity cravings",
      "Since our cakes are baked and decorated by hand once you place your order, the actual product might differ slightly from the photos provided here.",
      "Note: Please consume within 24 hours of receiving",
    ],
    reviews: [],
  },
  {
    id: "cupcake_sinful_chocolate",
    name: "Sinful Chocolate",
    desc: "Rich chocolate cupcake with chocolate frosting",
    minPrice: "Rs. 200",
    discount: "20%",
    discountedPrice: "Rs. 160",
    rating: 0,
    ratingNo: 0,
    images: ["/cupcakes/choco.webp", "/cupcakes/choco-2.webp"],
    flavour: [flavour.CHOCOLATE],
    occasion: occasion.NONE,
    category: category.CUPCAKE,
    type: type.NONE,
    sameDayDelivery: true,
    bestSeller: false,
    eggless: false,
    info: [
      "These Chocolate cupcakes are the ultimate party food. These are super moist and bursting with rich, chocolaty flavor.",
      "Since our cakes are baked and decorated by hand once you place your order, the actual product might differ slightly from the photos provided here.",
      "Note: Please consume within 24 hours of receiving",
    ],
    reviews: [],
  },
  {
    id: "cupcake_zesty_orange",
    name: "Zesty Orange",
    desc: "Zesty orange cupcakes with orange-flavoured buttercream",
    minPrice: "Rs. 200",
    rating: 0,
    ratingNo: 0,
    images: ["/cupcakes/orange.webp", "/cupcakes/orange-2.webp"],
    flavour: [flavour.FRUIT],
    occasion: occasion.NONE,
    category: category.CUPCAKE,
    type: type.NONE,
    sameDayDelivery: true,
    bestSeller: false,
    eggless: true,
    info: [
      "Fresh orange juice and zest gives these beautiful Orange Cupcakes a sweet, aromatic orange zing.",
      "Each cake is topped with a creamy orange buttercream.",
      "Since our cakes are baked and decorated by hand once you place your order, the actual product might differ slightly from the photos provided here.",
      "Note: Please consume within 24 hours of receiving",
    ],
    reviews: [],
  },
  {
    id: "cupcake_ruffle_love",
    name: "Ruffle Love",
    desc: "Chocolate ganache-filled cupcakes",
    minPrice: "Rs. 200",
    discount: "20%",
    discountedPrice: "Rs. 160",
    rating: 0,
    ratingNo: 0,
    images: ["/cupcakes/ruffle.webp", "/cupcakes/ruffle-2.jpeg"],
    flavour: [flavour.CHOCOLATE],
    occasion: occasion.NONE,
    category: category.CUPCAKE,
    type: type.NONE,
    sameDayDelivery: true,
    bestSeller: false,
    eggless: true,
    info: [
      "A fluffy chocolate cake, filled with semi-sweet chocolate ganache, and topped with cocoa whipped cream frosting.",
      "Since our cakes are baked and decorated by hand once you place your order, the actual product might differ slightly from the photos provided here.",
      "Note: Please consume within 24 hours of receiving",
    ],
    reviews: [],
  },
  {
    id: "cupcake_oreo",
    name: "Oreo Fling",
    desc: "Cupcakes topped with cookies n creme",
    minPrice: "Rs. 200",
    rating: 0,
    ratingNo: 0,
    images: ["/cupcakes/oreo.webp"],
    flavour: [flavour.CHOCOLATE, flavour.VANILLA],
    occasion: occasion.NONE,
    category: category.CUPCAKE,
    type: type.NONE,
    sameDayDelivery: true,
    bestSeller: false,
    eggless: false,
    priceList: [
      {
        flavour: flavour.VANILLA,
        price: "Rs. 200",
      },
      {
        flavour: flavour.CHOCOLATE,
        price: "Rs. 220",
      },
    ],
    info: [
      "These Oreo cupcakes have a spongy cupcake base which comes in both vanilla and chocolate flavours.",
      "These cakes are filled with white chocolate ganache and topped with cookies and cream.",
      "Since our cakes are baked and decorated by hand once you place your order, the actual product might differ slightly from the photos provided here.",
      "Note: Please consume within 24 hours of receiving",
    ],
    reviews: [],
  },
  {
    id: "cupcake_love_is_love",
    name: "Love is Love",
    desc: "Vanilla/Chocolate flavoured cupcakes with rainbow-colored frosting ",
    minPrice: "Rs. 200",
    discount: "20%",
    discountedPrice: "Rs. 160",
    rating: 0,
    ratingNo: 0,
    images: ["/cupcakes/rainbow.jpeg"],
    flavour: [flavour.CHOCOLATE],
    occasion: occasion.NONE,
    category: category.CUPCAKE,
    type: type.NONE,
    sameDayDelivery: true,
    bestSeller: false,
    eggless: true,
    priceList: [
      {
        flavour: flavour.VANILLA,
        price: "Rs. 200",
        discount: "20%",
        discountedPrice: "Rs. 160",
      },
      {
        flavour: flavour.CHOCOLATE,
        price: "Rs. 200",
        discount: "20%",
        discountedPrice: "Rs. 160",
      },
    ],
    info: [
      "Celebrate love and pride with these beautiful and vibrant cupcakes which comes with rainbow-colored fronsting",
      "Cake your pick from Vanilla and Chocolate flavours.",
      "Since our cakes are baked and decorated by hand once you place your order, the actual product might differ slightly from the photos provided here.",
      "Note: Please consume within 24 hours of receiving",
    ],
    reviews: [],
  },
  {
    id: "cupcake_choco_rush",
    name: "Choco Rush",
    desc: "Chocolate cupcake with chocochips-filled frosting",
    minPrice: "Rs. 200",
    discount: "20%",
    discountedPrice: "Rs. 160",
    rating: 0,
    ratingNo: 0,
    images: [
      "/cupcakes/choco-red.webp",
      "/cupcakes/choco-red-2.webp",
      "/cupcakes/choco-red-3.webp",
      "/cupcakes/choco-red-4.webp",
    ],
    flavour: [flavour.CHOCOLATE],
    occasion: occasion.NONE,
    category: category.CUPCAKE,
    type: type.NONE,
    sameDayDelivery: true,
    bestSeller: false,
    eggless: true,
    info: [
      "These cupcakes are rich, moist and chocolatey.",
      "They are topped with chocochips-filled frosting, and the perfect afterparty dessert.",
      "Since our cakes are baked and decorated by hand once you place your order, the actual product might differ slightly from the photos provided here.",
      "Note: Please consume within 24 hours of receiving",
    ],
    reviews: [],
  },
];
