const category = {
  none: "None",
  cake: "Cake",
  cupcake: "Cupcake",
  jarcake: "Jar Cake",
};

const flavour = {
  none: "None",
  chocolate: "Chocolate",
  vanilla: "Vanilla",
  strawberry: "Strawberry",
  redvelvet: "Red Velvet",
  fruit: "Fruit",
  blackforest: "Black Forest",
};

const type = {
  none: "None",
  fondant: "Fondant",
  pullup: "Pull-Up",
  bento: "Bento",
  mousse: "Mousse",
};

const occasion = {
  none: "None",
  birthday: "Birthday",
  wedding: "Wedding",
  anniversary: "Anniversary",
  christmas: "Christmas",
  valentines: "Valentine's Day",
};

/*** TEST DATA ***/

const test = {
  id: "cc_01",
  name: "Christmas Confetti",
  desc: "Chocolate Cupcake with Confetti",
  minPrice: "Rs. 200",
  discountedPrice: "Rs. 150",
  discount: "20%",
  rating: 4.5,
  ratingNo: 13,
  // images: [Christmas, Christmas2, Christmas3],
  flavour: ["chocolate", "vanilla", "strawberry"],
  occasion: "christmas",
  category: "cupcake",
  type: "none",
  sameDayDelivery: true,
  bestSeller: false,
  eggless: true,
  weight: ["500 gm", "1 kg"],
  priceList: [
    {
      weight: "500 gm",
      flavour: "chocolate",
      price: "Rs. 400",
      discountedPrice: "Rs. 320",
      discount: "20%",
    },
    {
      weight: "1 kg",
      flavour: "chocolate",
      price: "Rs. 450",
    },
    {
      weight: "500 gm",
      flavour: "vanilla",
      price: "Rs. 200",
    },
    {
      weight: "1 kg",
      flavour: "vanilla",
      price: "Rs. 250",
      discountedPrice: "Rs. 150",
      discount: "10%",
    },
    {
      weight: "500 gm",
      flavour: "strawberry",
      price: "Rs. 300",
    },
    {
      weight: "1 kg",
      flavour: "strawberry",
      price: "Rs. 350",
    },
  ],
  info: [
    "Our Christmas Confetti cake is the perfect dessert for your Christmas spread.",

    "This chocolate cupcake has a moist and soft base, topped with a dollop with confetti-filled buttercream.",

    "Since our cakes are baked and decorated by hand once you place your order, the actual product might differ slightly from the photos provided here.",

    "Note: Please consume within 24 hours of receiving.",
  ],
  reviews: [
    {
      name: "John Travolta",
      location: "Patna, Bihar",
      date: "24/10/2021",
      // images: [Christmas3],
      weight: null,
      flavour: null,
      text: "I ordered a cupcake and danced Salsa with it.",
    },
    {
      name: "LeBron James",
      location: "Patna, Bihar",
      date: "04/09/2021",
      // images: [Christmas, Christmas2],
      weight: null,
      flavour: null,
      text: "I ordered a cupcake and dunked it into the bin.",
    },
    {
      name: "Lionel Messy",
      location: "Kolkata, West Bengal",
      date: "20/09/2021",
      images: null,
      weight: null,
      flavour: null,
      text: "I ordered a cupcake and shot it in the goal.",
    },
  ],
};
/**** CUPCAKES *****/

export const cupcakes = [
  {
    id: "cupcake_christmas_confetti",
    name: "Christmas Confetti",
    desc: "Chocolate Cupcake sprinkled with Confetti",
    minPrice: "Rs. 250",
    discountedPrice: "Rs. 200",
    discount: "20%",
    rating: 5,
    ratingNo: 1,
    images: [
      "/cupcakes/christmas.webp",
      "/cupcakes/christmas-2.webp",
      "/cupcakes/christmas-3.webp",
    ],
    flavour: ["chocolate"],
    occasion: "christmas",
    category: "cupcake",
    type: "none",
    sameDayDelivery: true,
    bestSeller: true,
    eggless: true,
    info: [
      "Our Christmas Confetti cake is the perfect dessert for your Christmas spread.",
      "This chocolate cupcake has a moist and soft base, topped with a dollop of confetti-filled buttercream.",
      "Since our cakes are baked and decorated by hand once you place your order, the actual product might differ slightly from the photos provided here.",
      "Note: Please consume within 24 hours of receiving.",
    ],
    ratings: {
      1: 0,
      2: 0,
      3: 0,
      4: 0,
      5: 1,
    },
    reviews: [
      {
        name: "John Travolta",
        location: "Patna, Bihar",
        date: "Decemeber 24, 2021",
        rating: 5,
        images: ["/cupcakes/christmas.webp"],
        text: "This was the best Christmas cupcake I have ever had. It was so good that my dead neighbout came out of his grave to take a bite.",
      },
    ],
  },
  {
    id: "cupcake_classic_red_velvet",
    name: "Classic Red Velvet",
    desc: "Classic red velvet cupcake",
    minPrice: "Rs. 250",
    rating: 4,
    ratingNo: 6,
    images: [
      "/cupcakes/redvelvet.webp",
      "/cupcakes/redvelvet-2.webp",
      "/cupcakes/redvelvet-3.webp",
    ],
    flavour: ["redvelvet"],
    occasion: "none",
    category: "cupcake",
    type: "none",
    sameDayDelivery: true,
    bestSeller: false,
    eggless: false,
    info: [
      "Our Classic Red Velvet cupcake is the forever-favourite red velvet cake topped with a delicious frosting, sprinkled with chocochips and confetti.",
      "Since our cakes are baked and decorated by hand once you place your order, the actual product might differ slightly from the photos provided here.",
      "Note: Please consume within 24 hours of receiving.",
    ],
    reviews: [],
  },
  {
    id: "cupcake_happy_halloween",
    name: "Happy Halloween",
    desc: "Halloween-themed vanilla/chocolate cupcake",
    minPrice: "Rs. 200",
    discount: "20%",
    discountedPrice: "Rs. 160",
    rating: 5,
    ratingNo: 12,
    images: [
      "/cupcakes/halloween.webp",
      "/cupcakes/halloween-2.jpeg",
      "/cupcakes/halloween-3.webp",
    ],
    flavour: ["vanilla", "chocolate"],
    occasion: "none",
    category: "cupcake",
    type: "none",
    sameDayDelivery: false,
    bestSeller: false,
    eggless: true,
    priceList: [
      {
        flavour: "vanilla",
        price: "Rs. 200",
        discount: "20%",
        discountedPrice: "Rs. 160",
      },
      {
        flavour: "chocolate",
        price: "Rs. 220",
        discount: "20%",
        discountedPrice: "Rs. 175",
      },
    ],
    info: [
      "Add a dash of delicious fun to your kid's halloween party with our Halloween-themed cupcakes",
      "Take your pick between Vanilla and Chocolate flavours.",
      "Since our cakes are baked and decorated by hand once you place your order, the actual product might differ slightly from the photos provided here.",
      "Note: Please consume within 24 hours of receiving.",
    ],
    reviews: [],
  },
  {
    id: "cupcake_zingy_lemon",
    name: "Zingy Lemon",
    desc: "Lemon flavoured cupcake with lemon icing",
    minPrice: "Rs. 200",
    rating: 3,
    ratingNo: 4,
    images: ["/cupcakes/lemon.jpeg", "/cupcakes/lemon-2.jpeg"],
    flavour: ["fruit"],
    occasion: "none",
    category: "cupcake",
    type: "none",
    sameDayDelivery: false,
    bestSeller: false,
    eggless: true,
    info: [
      "These easy lemon cupcakes are moist, fluffy, zingy and topped with an incredible lemon buttercream that's a lemon-lover's dream!",
      "Since our cakes are baked and decorated by hand once you place your order, the actual product might differ slightly from the photos provided here.",
      "Note: Please consume within 24 hours of receiving.",
    ],
    reviews: [],
  },
  {
    id: "cupcake_matcha_magic",
    name: "Matcha Magic",
    desc: "Matcha green tea flavoured cupcakes",
    minPrice: "Rs. 200",
    discount: "20%",
    discountedPrice: "Rs. 160",
    rating: 0,
    ratingNo: 0,
    images: ["/cupcakes/matcha.webp"],
    flavour: ["vanilla", "chocolate"],
    occasion: "none",
    category: "cupcake",
    type: "none",
    sameDayDelivery: false,
    bestSeller: false,
    eggless: false,
    priceList: [
      {
        flavour: "vanilla",
        price: "Rs. 200",
        discount: "20%",
        discountedPrice: "Rs. 160",
      },
      {
        flavour: "chocolate",
        price: "Rs. 220",
        discount: "20%",
        discountedPrice: "Rs. 175",
      },
    ],
    info: [
      "Soft and fluffy Matcha Green Tea Cupcakes topped with a white cloud of vanilla whipped cream taste just like a Matcha green tea Frappuccino!",
      "Since our cakes are baked and decorated by hand once you place your order, the actual product might differ slightly from the photos provided here.",
      "Note: Please consume within 24 hours of receiving.",
    ],
    reviews: [],
  },
  {
    id: "cupcake_baby_blue",
    name: "Baby Blue",
    desc: "Vanilla cupcake with teal frosting",
    minPrice: "Rs. 250",
    rating: 0,
    ratingNo: 0,
    images: ["/cupcakes/teal.webp"],
    flavour: ["vanilla"],
    occasion: "none",
    category: "cupcake",
    type: "none",
    sameDayDelivery: true,
    bestSeller: false,
    eggless: false,
    info: [
      "These delicious snowy super moist chocolate cupcakes with blue buttercream frosting are here to brighten up your winter holidays!",
      "Since our cakes are baked and decorated by hand once you place your order, the actual product might differ slightly from the photos provided here.",
      "Note: Please consume within 24 hours of receiving.",
    ],
    reviews: [],
  },
  {
    id: "cupcake_peachy_tropicana",
    name: "Peachy Tropicana",
    desc: "Peachy flavoured cupcakes",
    minPrice: "Rs. 200",
    discount: "20%",
    discountedPrice: "Rs. 160",
    rating: 4.5,
    ratingNo: 16,
    images: [
      "/cupcakes/peach.webp",
      "/cupcakes/peach-2.webp",
      "/cupcakes/peach-3.webp",
    ],
    flavour: ["fruit"],
    occasion: "none",
    category: "cupcake",
    type: "none",
    sameDayDelivery: true,
    bestSeller: true,
    eggless: true,
    info: [
      "These peach-flavoured cupcakes with soft, peachy frosting are here to satiate your fruity cravings",
      "Since our cakes are baked and decorated by hand once you place your order, the actual product might differ slightly from the photos provided here.",
      "Note: Please consume within 24 hours of receiving.",
    ],
    reviews: [],
  },
  {
    id: "cupcake_sinful_chocolate",
    name: "Sinful Chocolate",
    desc: "Rich chocolate cupcake with chocolate frosting",
    minPrice: "Rs. 200",
    discount: "20%",
    discountedPrice: "Rs. 160",
    rating: 5,
    ratingNo: 15,
    images: ["/cupcakes/choco.webp", "/cupcakes/choco-2.webp"],
    flavour: ["chocolate"],
    occasion: "none",
    category: "cupcake",
    type: "none",
    sameDayDelivery: true,
    bestSeller: true,
    eggless: false,
    info: [
      "These Chocolate cupcakes are the ultimate party food. These are super moist and bursting with rich, chocolaty flavor.",
      "Since our cakes are baked and decorated by hand once you place your order, the actual product might differ slightly from the photos provided here.",
      "Note: Please consume within 24 hours of receiving.",
    ],
    reviews: [],
  },
  {
    id: "cupcake_zesty_orange",
    name: "Zesty Orange",
    desc: "Zesty orange cupcakes with orange-flavoured buttercream",
    minPrice: "Rs. 200",
    rating: 0,
    ratingNo: 0,
    images: ["/cupcakes/orange.webp", "/cupcakes/orange-2.webp"],
    flavour: ["fruit"],
    occasion: "none",
    category: "cupcake",
    type: "none",
    sameDayDelivery: true,
    bestSeller: false,
    eggless: true,
    info: [
      "Fresh orange juice and zest gives these beautiful Orange Cupcakes a sweet, aromatic orange zing.",
      "Each cake is topped with a creamy orange buttercream.",
      "Since our cakes are baked and decorated by hand once you place your order, the actual product might differ slightly from the photos provided here.",
      "Note: Please consume within 24 hours of receiving.",
    ],
    reviews: [],
  },
  {
    id: "cupcake_ruffle_love",
    name: "Ruffle Love",
    desc: "Chocolate ganache-filled cupcakes",
    minPrice: "Rs. 200",
    discount: "20%",
    discountedPrice: "Rs. 160",
    rating: 3.5,
    ratingNo: 6,
    images: ["/cupcakes/ruffle.webp", "/cupcakes/ruffle-2.jpeg"],
    flavour: ["chocolate"],
    occasion: "none",
    category: "cupcake",
    type: "none",
    sameDayDelivery: true,
    bestSeller: false,
    eggless: true,
    info: [
      "A fluffy chocolate cake, filled with semi-sweet chocolate ganache, and topped with cocoa whipped cream frosting.",
      "Since our cakes are baked and decorated by hand once you place your order, the actual product might differ slightly from the photos provided here.",
      "Note: Please consume within 24 hours of receiving.",
    ],
    reviews: [],
  },
  {
    id: "cupcake_oreo",
    name: "Oreo Fling",
    desc: "Cupcakes topped with cookies n creme",
    minPrice: "Rs. 200",
    rating: 4,
    ratingNo: 8,
    images: ["/cupcakes/oreo.webp"],
    flavour: ["chocolate", "vanilla"],
    occasion: "none",
    category: "cupcake",
    type: "none",
    sameDayDelivery: true,
    bestSeller: true,
    eggless: false,
    priceList: [
      {
        flavour: "vanilla",
        price: "Rs. 200",
      },
      {
        flavour: "chocolate",
        price: "Rs. 220",
      },
    ],
    info: [
      "These Oreo cupcakes have a spongy cupcake base which comes in both vanilla and chocolate flavours.",
      "These cakes are filled with white chocolate ganache and topped with cookies and cream.",
      "Since our cakes are baked and decorated by hand once you place your order, the actual product might differ slightly from the photos provided here.",
      "Note: Please consume within 24 hours of receiving.",
    ],
    reviews: [],
  },
  {
    id: "cupcake_love_is_love",
    name: "Love is Love",
    desc: "Vanilla/Chocolate flavoured cupcakes with rainbow-colored frosting ",
    minPrice: "Rs. 200",
    discount: "20%",
    discountedPrice: "Rs. 160",
    rating: 0,
    ratingNo: 0,
    images: ["/cupcakes/rainbow.jpeg"],
    flavour: ["chocolate"],
    occasion: "none",
    category: "cupcake",
    type: "none",
    sameDayDelivery: true,
    bestSeller: false,
    eggless: true,
    priceList: [
      {
        flavour: "vanilla",
        price: "Rs. 200",
        discount: "20%",
        discountedPrice: "Rs. 160",
      },
      {
        flavour: "chocolate",
        price: "Rs. 200",
        discount: "20%",
        discountedPrice: "Rs. 160",
      },
    ],
    info: [
      "Celebrate love and pride with these beautiful and vibrant cupcakes which comes with rainbow-colored fronsting",
      "Cake your pick from Vanilla and Chocolate flavours.",
      "Since our cakes are baked and decorated by hand once you place your order, the actual product might differ slightly from the photos provided here.",
      "Note: Please consume within 24 hours of receiving.",
    ],
    reviews: [],
  },
  {
    id: "cupcake_choco_rush",
    name: "Choco Rush",
    desc: "Chocolate cupcake with chocochips-filled frosting",
    minPrice: "Rs. 200",
    discount: "20%",
    discountedPrice: "Rs. 160",
    rating: 0,
    ratingNo: 0,
    images: [
      "/cupcakes/choco-red.webp",
      "/cupcakes/choco-red-2.webp",
      "/cupcakes/choco-red-3.webp",
      "/cupcakes/choco-red-4.webp",
    ],
    flavour: ["chocolate"],
    occasion: "none",
    category: "cupcake",
    type: "none",
    sameDayDelivery: true,
    bestSeller: false,
    eggless: true,
    info: [
      "These cupcakes are rich, moist and chocolatey.",
      "They are topped with chocochips-filled frosting, and the perfect afterparty dessert.",
      "Since our cakes are baked and decorated by hand once you place your order, the actual product might differ slightly from the photos provided here.",
      "Note: Please consume within 24 hours of receiving.",
    ],
    reviews: [],
  },
];

/***** CAKES *****/

export const cakes = [
  /**** WEDDING CAKES ****/
  {
    id: "wedding_vintage_fruit_delight",
    name: "Vintage Fruit Delight",
    desc: "Buttercream covered wedding cake with chocolate drip",
    minPrice: "Rs. 6,500",
    discountedPrice: "Rs. 5,525",
    discount: "15%",
    rating: 4.5,
    ratingNo: 7,
    images: ["/cakes/wedding1-1.jpeg", "/cakes/wedding1-2.webp"],
    flavour: ["chocolate", "vanilla", "blackforest"],
    occasion: "wedding",
    category: "cake",
    type: "none",
    sameDayDelivery: false,
    bestSeller: false,
    eggless: true,
    weight: ["3 kg", "4 kg"],
    priceList: [
      {
        weight: "3 kg",
        flavour: "vanilla",
        price: "Rs. 6,500",
        discountedPrice: "Rs. 5,525",
        discount: "15%",
      },
      {
        weight: "4 kg",
        flavour: "vanilla",
        price: "Rs. 7,200",
        discountedPrice: "Rs. 6,120",
        discount: "15%",
      },
      {
        weight: "3 kg",
        flavour: "chocolate",
        price: "Rs. 6,500",
        discountedPrice: "Rs. 5,525",
        discount: "15%",
      },
      {
        weight: "4 kg",
        flavour: "chocolate",
        price: "Rs. 7,200",
        discountedPrice: "Rs. 6,120",
        discount: "15%",
      },
      {
        weight: "3 kg",
        flavour: "blackforest",
        price: "Rs. 7,000",
        discountedPrice: "Rs. 5,950",
        discount: "15%",
      },
      {
        weight: "4 kg",
        flavour: "blackforest",
        price: "Rs. 7,600",
        discountedPrice: "Rs. 6,460",
        discount: "15%",
      },
    ],
    info: [
      "Make your grandest day even more grand with our vintage buttercream-covered wedding cake.",

      "The cake is decorated with fresh fruits and dripping chocolate ganache.",

      "Since our cakes are baked and decorated by hand once you place your order, the actual product might differ slightly from the photos provided here.",

      "Note: Please consume within 24 hours of receiving.",
    ],
    ratings: {
      1: 0,
      2: 0,
      3: 1,
      4: 2,
      5: 4,
    },
    reviews: [
      {
        name: "Rishika Malik",
        location: "Gurgaon, Haryana",
        date: "October 19, 2021",
        rating: 4,
        images: ["/reviews/wedding1-r1.jpeg", "/reviews/wedding1-r2.jpeg"],
        title: "Made my day!",
        text: "The cake was perfect. All the guests really enjoyed it.",
      },
      {
        name: "Prithwa Agarwal",
        location: "Kolkata, West Bengal",
        date: "January 19, 2021",
        rating: 4,
        title: "The cake was gorgeous.",
        text: "After going through a lot of options, I finally chose this royal cake for my big day. The cake was delicious and extremely pretty. The fruits were fresh and the buttercream was just the right amouut of sweet and creamy. The Cake Bar & Co. team was in touch with me throughout the process, and made the experience extremely hassle-free",
      },
      {
        name: "Rosey Diaz",
        location: "Vaizag, Andhra Pradesh",
        date: "October 17, 2020",
        rating: 5,
        images: ["/reviews/wedding1-r3.jpeg"],
        title: "Beautiful and delicious!",
        text: "My wedding cake was the star of the evening. The cake was as tasty as it was beautiful, and the service from the team was pariseworthy.",
      },
    ],
  },
  {
    id: "wedding_ice_and_gold",
    name: "Ice and Gold",
    desc: "Buttercream covered wedding cake decorated with gold foil",
    minPrice: "Rs. 7,200",
    discountedPrice: "Rs. 6,120",
    discount: "15%",
    rating: 4.5,
    ratingNo: 6,
    images: ["/cakes/wedding2-2.jpeg", "/cakes/wedding2-1.webp"],
    flavour: ["chocolate", "vanilla"],
    occasion: "wedding",
    category: "cake",
    type: "none",
    sameDayDelivery: false,
    bestSeller: false,
    eggless: true,
    weight: ["3 kg", "4 kg"],
    priceList: [
      {
        weight: "3 kg",
        flavour: "vanilla",
        price: "Rs. 7,200",
        discountedPrice: "Rs. 6,120",
        discount: "15%",
      },
      {
        weight: "4 kg",
        flavour: "vanilla",
        price: "Rs. 7,800",
        discountedPrice: "Rs. 6,630",
        discount: "15%",
      },
      {
        weight: "3 kg",
        flavour: "chocolate",
        price: "Rs. 7,200",
        discountedPrice: "Rs. 6,120",
        discount: "15%",
      },
      {
        weight: "4 kg",
        flavour: "chocolate",
        price: "Rs. 7,800",
        discountedPrice: "Rs. 6,630",
        discount: "15%",
      },
    ],
    info: [
      "This 3-tier wedding cake in available in both vanilla and chocolate flavours.",

      "The gradient of icy-blue buttercream, along with pieces of gold foil, gives this cake a royal touch.",

      "Since our cakes are baked and decorated by hand once you place your order, the actual product might differ slightly from the photos provided here.",

      "Note: Please consume within 24 hours of receiving.",
    ],
    ratings: {
      1: 0,
      2: 0,
      3: 0,
      4: 3,
      5: 3,
    },
    reviews: [],
  },
  {
    id: "wedding_heaven_on_earth",
    name: "Heaven on Earth",
    desc: "A flower-studded 4-tiered wedding cake",
    minPrice: "Rs. 8,000",
    discountedPrice: "Rs. 7,200",
    discount: "10%",
    rating: 5,
    ratingNo: 4,
    images: ["/cakes/wedding3-1.jpeg", "/cakes/wedding3-2.jpeg"],
    flavour: ["vanilla", "strawberry"],
    occasion: "wedding",
    category: "cake",
    type: "none",
    sameDayDelivery: false,
    bestSeller: false,
    eggless: true,
    weight: ["3 kg", "3.5 kg", "4 kg"],
    priceList: [
      {
        weight: "3 kg",
        flavour: "vanilla",
        price: "Rs. 8,000",
        discountedPrice: "Rs. 7,200",
        discount: "10%",
      },
      {
        weight: "3.5 kg",
        flavour: "vanilla",
        price: "Rs. 8,500",
        discountedPrice: "Rs. 7,650",
        discount: "10%",
      },
      {
        weight: "4 kg",
        flavour: "vanilla",
        price: "Rs. 9,000",
        discountedPrice: "Rs. 8,100",
        discount: "10%",
      },
      {
        weight: "3 kg",
        flavour: "strawberry",
        price: "Rs. 8,200",
        discountedPrice: "Rs. 7,216",
        discount: "12%",
      },
      {
        weight: "3.5 kg",
        flavour: "strawberry",
        price: "Rs. 8,700",
        discountedPrice: "Rs. 7,830",
        discount: "10%",
      },
      {
        weight: "4 kg",
        flavour: "strawberry",
        price: "Rs. 9,500",
        discountedPrice: "Rs. 8,075",
        discount: "15%",
      },
    ],
    info: [
      "This majestic cake is decorated with fresh flowers. The embossed self-colored patterns give this cake a subtle yet classy look.",

      "The cake is engraved with the initials of the couple in a golden hue.",

      "The 3 kg variant will be 3-tiered, and the 3.5 kg and 4 kg variants are 4-tiered.",

      "Since our cakes are baked and decorated by hand once you place your order, the actual product might differ slightly from the photos provided here.",

      "Note: Please consume within 24 hours of receiving.",
    ],
    ratings: {
      4: 2,
      5: 2,
    },
    reviews: [],
  },
  {
    id: "wedding_magical_marble",
    name: "Magical Marble",
    desc: "Marble-textured fondant cake",
    minPrice: "Rs. 7,200",
    discountedPrice: "Rs. 6,120",
    discount: "15%",
    rating: 0,
    ratingNo: 0,
    images: ["/cakes/wedding4-1.jpeg"],
    flavour: ["chocolate", "vanilla"],
    occasion: "wedding",
    category: "cake",
    type: "none",
    sameDayDelivery: false,
    bestSeller: false,
    eggless: true,
    weight: ["3 kg", "4 kg"],
    priceList: [
      {
        weight: "3 kg",
        flavour: "vanilla",
        price: "Rs. 7,200",
        discountedPrice: "Rs. 6,120",
        discount: "15%",
      },
      {
        weight: "4 kg",
        flavour: "vanilla",
        price: "Rs. 7,800",
        discountedPrice: "Rs. 6,630",
        discount: "15%",
      },
      {
        weight: "3 kg",
        flavour: "chocolate",
        price: "Rs. 7,200",
        discountedPrice: "Rs. 6,120",
        discount: "15%",
      },
      {
        weight: "4 kg",
        flavour: "chocolate",
        price: "Rs. 7,800",
        discountedPrice: "Rs. 6,630",
        discount: "15%",
      },
    ],
    info: [
      "This 3-tier wedding cake is beautifully wrapped in marble-textured fondant",

      "The gold pipings along the borders give this cake a unique and elegant look. The cake is decorated with fresh pastel-colored roses.",

      "Since our cakes are baked and decorated by hand once you place your order, the actual product might differ slightly from the photos provided here.",

      "Note: Please consume within 24 hours of receiving.",
    ],
    ratings: {},
    reviews: [],
  },

  /**** CHOCOLATE CAKES ****/
  {
    id: "cake_choco_drip",
    name: "Chocolate Drip Cake",
    desc: "Chocolate flavoured cake with dark chocolate drip",
    minPrice: "Rs. 500",
    rating: 0,
    ratingNo: 0,
    images: [
      "/cakes/choco-drip-1.webp",
      "/cakes/choco-drip-2.webp",
      "/cakes/choco-drip-3.webp",
    ],
    flavour: ["chocolate"],
    occasion: "none",
    category: "cake",
    type: "none",
    sameDayDelivery: false,
    bestSeller: false,
    eggless: false,
    weight: ["700 gm", "1 kg"],
    priceList: [
      {
        weight: "700 gm",
        price: "Rs. 500",
      },
      {
        weight: "1 kg",
        price: "Rs. 800",
      },
    ],
    info: [
      "A soft and flavourful cake, rich in chocolate. Topped with dripping ganache made with dark chocolate.",

      "Since our cakes are baked and decorated by hand once you place your order, the actual product might differ slightly from the photos provided here.",

      "Note: Please consume within 24 hours of receiving.",
    ],
    ratings: {},
    reviews: [],
  },
  {
    id: "cake_choco_fruit",
    name: "Chocolate Fruit Cake",
    desc: "Chocolate flavoured cake topped with fresh fruits",
    minPrice: "Rs. 500",
    rating: 0,
    ratingNo: 0,
    images: ["/cakes/choco-fruit-2.webp", "/cakes/choco-fruit-1.jpeg"],
    flavour: ["chocolate"],
    occasion: ["birthday"],
    category: "cake",
    type: "none",
    sameDayDelivery: false,
    bestSeller: false,
    eggless: false,
    weight: ["700 gm", "1 kg"],
    priceList: [
      {
        weight: "750 gm",
        price: "Rs. 500",
      },
      {
        weight: "1 kg",
        price: "Rs. 800",
      },
    ],
    info: [
      "A rich chocolatey cake with soft and moist base. Topped with chocolate ganache and fresh fruits.",

      "Since our cakes are baked and decorated by hand once you place your order, the actual product might differ slightly from the photos provided here.",

      "Note: Please consume within 24 hours of receiving.",
    ],
    ratings: {},
    reviews: [],
  },
  {
    id: "cake_choco_mousse",
    name: "Chocolate Mousse Cake",
    desc: "Chocolate mousse cake with chocolates and nuts topping",
    minPrice: "Rs. 700",
    rating: 0,
    ratingNo: 0,
    images: ["/cakes/choco-mousse-1.jpeg", "/cakes/choco-mousse-2.jpeg"],
    flavour: ["chocolate"],
    occasion: "none",
    category: "cake",
    type: "none",
    sameDayDelivery: false,
    bestSeller: false,
    eggless: false,
    weight: ["600 gm", "1 kg"],
    priceList: [
      {
        weight: "600 gm",
        price: "Rs. 700",
      },
      {
        weight: "1 kg",
        price: "Rs. 900",
      },
    ],
    info: [
      "Our rich mousse cake with a biscotti base is a staple dessert for chocolate lovers. It is topped with an assortment of chocolates and nuts.",

      "Take a mouthful of our soft, creamy mousse cake and relish it melting in your mouth.",

      "Since our cakes are baked and decorated by hand once you place your order, the actual product might differ slightly from the photos provided here.",

      "Note: Please consume within 24 hours of receiving.",
    ],
    ratings: {},
    reviews: [],
  },
  {
    id: "cake_layered_choco_mousse",
    name: "Layered Choco Mousse Cake",
    desc: "Chocolate mousse cake with 3 layers",
    minPrice: "Rs. 800",
    discountedPrice: "Rs. 640",
    discount: "20%",
    rating: 0,
    ratingNo: 0,
    images: ["/cakes/mousse-1.webp", "/cakes/mousse-2.webp"],
    flavour: ["chocolate"],
    occasion: "none",
    category: "cake",
    type: "none",
    sameDayDelivery: false,
    bestSeller: false,
    eggless: false,
    weight: ["600 gm", "1 kg"],
    priceList: [
      {
        weight: "600 gm",
        price: "Rs. 800",
        discountedPrice: "Rs. 640",
        discount: "20%",
      },
      {
        weight: "1 kg",
        price: "Rs. 900",
        discountedPrice: "Rs. 720",
        discount: "20%",
      },
    ],
    info: [
      "Our layered mousse cake with an Oreo base has 3 layers - white chocoalte, milk chocolate and dark chocolate.",

      "Enjoy the soft, creamy deliciousness of the perfect mousse cake as it gently melts in your palate.",

      "Since our cakes are baked and decorated by hand once you place your order, the actual product might differ slightly from the photos provided here.",

      "Note: Please consume within 24 hours of receiving.",
    ],
    ratings: {},
    reviews: [],
  },
  {
    id: "cake_choco_pinata",
    name: "Chocolate Pinata Cake",
    desc: "Heart-shaped chocolate pinata cake",
    minPrice: "Rs. 800",
    discountedPrice: "Rs. 640",
    discount: "20%",
    rating: 0,
    ratingNo: 0,
    images: ["/cakes/choco-pinata.jpeg", "/cakes/choco-pinata-2.jpeg"],
    flavour: ["chocolate"],
    occasion: "none",
    category: "cake",
    type: "none",
    sameDayDelivery: false,
    bestSeller: false,
    eggless: false,
    weight: ["1 kg"],
    info: [
      "Make any celebration fun with our heart-shaped Chocolate Pinata cake. Break it with the hammer provided, and enjoy the lip-smacking cake inside.",

      "The inside of the shells contains a heart-shaped soft, moist chocolate cake filled with choco-chips.",

      "Since our cakes are baked and decorated by hand once you place your order, the actual product might differ slightly from the photos provided here.",

      "Note: Please consume within 24 hours of receiving.",
    ],
    ratings: {},
    reviews: [],
  },
  {
    id: "cake_for_the_love_of_chocolate",
    name: "For the Love of Chocolate",
    desc: "Classic chocolate cake with dark chocolate ganache coating",
    minPrice: "Rs. 800",
    discountedPrice: "Rs. 640",
    discount: "20%",
    rating: 0,
    ratingNo: 0,
    images: ["/cakes/choco-simple-1.webp", "/cakes/choco-simple-2.jpeg"],
    flavour: ["chocolate"],
    occasion: "none",
    category: "cake",
    type: "none",
    sameDayDelivery: false,
    bestSeller: false,
    eggless: false,
    weight: ["750 gm", "1 kg"],
    priceList: [
      {
        weight: "750 gm",
        price: "Rs. 800",
        discountedPrice: "Rs. 640",
        discount: "20%",
      },
      {
        weight: "1 kg",
        price: "Rs. 900",
        discountedPrice: "Rs. 720",
        discount: "20%",
      },
    ],
    info: [
      "This simple, rich chocolate cake, coated with dark chocolate ganache, is the go to dessert for every party.",

      "Since our cakes are baked and decorated by hand once you place your order, the actual product might differ slightly from the photos provided here.",

      "Note: Please consume within 24 hours of receiving.",
    ],
    ratings: {},
    reviews: [],
  },
  {
    id: "cake_ferrero",
    name: "Ferrero Delight",
    desc: "Chocolate cake topped with Ferrero Rocher",
    minPrice: "Rs. 1000",
    discountedPrice: "Rs. 850",
    discount: "15%",
    rating: 0,
    ratingNo: 0,
    images: [
      "/cakes/ferrero-1.webp",
      "/cakes/ferrero-2.png",
      "/cakes/ferrero-3.webp",
    ],
    flavour: ["chocolate"],
    occasion: "none",
    category: "cake",
    type: "none",
    sameDayDelivery: false,
    bestSeller: false,
    eggless: true,
    weight: ["1 kg", "1.5 kg"],
    priceList: [
      {
        weight: "1 kg",
        price: "Rs. 1000",
        discountedPrice: "Rs. 850",
        discount: "15%",
      },
      {
        weight: "1.5 kg",
        price: "Rs. 1500",
        discountedPrice: "Rs. 1,275",
        discount: "15%",
      },
    ],
    info: [
      "This simple, rich chocolate cake, coated with dark chocolate ganache, is topped with everybody's favourite chocolate - Ferrero Rocher. This is the go to dessert for every party.",

      "Since our cakes are baked and decorated by hand once you place your order, the actual product might differ slightly from the photos provided here.",

      "Note: Please consume within 24 hours of receiving.",
    ],
    ratings: {},
    reviews: [],
  },
  {
    id: "cake_german_chocolate",
    name: "German Chocolate Cake",
    desc: "Meringue-topped German chocolate cake",
    minPrice: "Rs. 1000",
    discountedPrice: "Rs. 850",
    discount: "15%",
    rating: 0,
    ratingNo: 0,
    images: [
      "/cakes/german-chocolate.webp",
      "/cakes/german-chocolate-2.jpeg",
      "/cakes/german-chocolate-3.jpeg",
    ],
    flavour: ["chocolate"],
    occasion: "none",
    category: "cake",
    type: "none",
    sameDayDelivery: false,
    bestSeller: false,
    eggless: false,
    weight: ["1 kg", "1.5 kg"],
    priceList: [
      {
        weight: "1 kg",
        price: "Rs. 1000",
        discountedPrice: "Rs. 900",
        discount: "10%",
      },
      {
        weight: "1.5 kg",
        price: "Rs. 1500",
        discountedPrice: "Rs. 1,275",
        discount: "15%",
      },
    ],
    info: [
      "German chocolate cake is a layered chocolate cake that's traditionally made with sweet baking chocolate and buttermilk.",
      "It's filled and topped with a frosting made from pecan, coconut, and evaporated milk.",

      "Since our cakes are baked and decorated by hand once you place your order, the actual product might differ slightly from the photos provided here.",

      "Note: Please consume within 24 hours of receiving.",
    ],
    ratings: {},
    reviews: [],
  },
  {
    id: "cake_berry_heart",
    name: "Heart of Berries",
    desc: "Heart-shaped cake topped with berries",
    minPrice: "Rs. 700",
    rating: 0,
    ratingNo: 0,
    images: ["/cakes/heart-berry.jpeg", "/cakes/heart-berry-2.jpeg"],
    flavour: ["redvelvet", "vanilla"],
    occasion: ["valentines", "anniversary"],
    category: "cake",
    type: "none",
    sameDayDelivery: false,
    bestSeller: false,
    eggless: false,
    weight: ["650 gm", "1 kg"],
    priceList: [
      {
        flavour: "vanilla",
        weight: "650 gm",
        price: "Rs. 700",
      },
      {
        flavour: "vanilla",
        weight: "1 kg",
        price: "Rs. 900",
      },
      {
        flavour: "redvelvet",
        weight: "650 gm",
        price: "Rs. 700",
      },
      {
        flavour: "redvelvet",
        weight: "1 kg",
        price: "Rs. 900",
      },
    ],
    info: [
      "Perfect for anniversaries, date nights and Valentine's Day, our heart-shaped cake is here to make you fall in love all over again.",

      "The cake base is soft and moist, available in Vanilla and Red Velvet flavours. It is topped with fresh cream and berries.",

      "Since our cakes are baked and decorated by hand once you place your order, the actual product might differ slightly from the photos provided here.",

      "Note: Please consume within 24 hours of receiving.",
    ],
    ratings: {},
    reviews: [],
  },
  {
    id: "cake_choco_heart",
    name: "Heart of Chocolate",
    desc: "Heart-shaped cake topped with strawberries",
    minPrice: "Rs. 700",
    rating: 0,
    ratingNo: 0,
    images: ["/cakes/heart-choco.jpeg", "/cakes/heart-choco-2.webp"],
    flavour: ["chocolate"],
    occasion: ["valentines", "anniversary"],
    category: "cake",
    type: "none",
    sameDayDelivery: false,
    bestSeller: false,
    eggless: false,
    weight: ["650 gm", "1 kg"],
    priceList: [
      {
        flavour: "vanilla",
        weight: "650 gm",
        price: "Rs. 700",
      },
      {
        flavour: "vanilla",
        weight: "1 kg",
        price: "Rs. 900",
      },
      {
        flavour: "redvelvet",
        weight: "650 gm",
        price: "Rs. 700",
      },
      {
        flavour: "redvelvet",
        weight: "1 kg",
        price: "Rs. 900",
      },
    ],
    info: [
      "Share this beautiful heart-shaped cake with your person, and fall in love all over again.",

      "The soft and fluffy cake is coated with a rich layer of chocolate ganache, and topped with freshly cut strawberries.",

      "Since our cakes are baked and decorated by hand once you place your order, the actual product might differ slightly from the photos provided here.",

      "Note: Please consume within 24 hours of receiving.",
    ],
    ratings: {},
    reviews: [],
  },
  {
    id: "cake_rose",
    name: "Roses For My Love",
    desc: "Strawberry cake covered with rose-flavoured buttercream",
    minPrice: "Rs. 1000",
    discountedPrice: "Rs. 850",
    discount: "15%",
    rating: 0,
    ratingNo: 0,
    images: ["/cakes/rose-1.jpeg", "/cakes/rose-2.webp", "/cakes/rose-3.webp"],
    flavour: ["strawberry"],
    occasion: ["anniversary", "valentines", "birthday"],
    category: "cake",
    type: "none",
    sameDayDelivery: false,
    bestSeller: false,
    eggless: false,
    weight: ["1 kg", "1.5 kg"],
    priceList: [
      {
        weight: "1 kg",
        price: "Rs. 1000",
        discountedPrice: "Rs. 850",
        discount: "15%",
      },
      {
        weight: "1.5 kg",
        price: "Rs. 1500",
        discountedPrice: "Rs. 1,275",
        discount: "15%",
      },
    ],
    info: [
      "This strawberry-flavoured cake is sure to make your heart melt with it's beautiful buttercream decorations. As pretty as a rose, indeed!",

      "Since our cakes are baked and decorated by hand once you place your order, the actual product might differ slightly from the photos provided here.",

      "Note: Please consume within 24 hours of receiving.",
    ],
    ratings: {},
    reviews: [],
  },
  {
    id: "cake_strawberry_shortcake",
    name: "Strawberry Shortcake",
    desc: "The classic strawbery shortcake",
    minPrice: "Rs. 500",
    discountedPrice: "Rs. 400",
    discount: "20%",
    rating: 0,
    ratingNo: 0,
    images: [
      "/cakes/strawberry-shortcake-1.jpeg",
      "/cakes/strawberry-shortcake-2.jpeg",
    ],
    flavour: ["strawberry"],
    occasion: "none",
    category: "cake",
    type: "none",
    sameDayDelivery: false,
    bestSeller: false,
    eggless: true,
    weight: ["500 gm"],
    info: [
      "Shortcake generally refers to a dessert with a crumbly scone like texture, and are usually served with fruit and cream.",

      "One of the most popular variation is strawberry shortcake, which is typically served with freshly cut strawberries and whipped cream.",

      "Since our cakes are baked and decorated by hand once you place your order, the actual product might differ slightly from the photos provided here.",

      "Note: Please consume within 24 hours of receiving.",
    ],
    ratings: {},
    reviews: [],
  },
];
