import Rose1 from "../assets/cakes/rose-1.jpeg";
import German1 from "../assets/cakes/german-chocolate.webp";
import HeartChoco from "../assets/cakes/heart-choco.jpeg";

export let cartItems = [
  {
    id: "cake_rose",
    name: "Roses For My Love",
    price: "Rs. 1000",
    discountedPrice: "Rs. 850",
    discount: "15%",
    qty: 1,
    image: Rose1,
    flavour: "Strawberry",
    bestSeller: false,
    eggless: false,
    weight: "1 kg",
    delivery: "19 January 2023",
  },
  {
    id: "cake_choco_heart",
    name: "Heart of Chocolate",
    price: "Rs. 800",
    qty: 2,
    image: HeartChoco,
    flavour: "Chocolate",
    bestSeller: true,
    eggless: true,
    weight: "1.5 kg",
    delivery: "25 February 2023",
  },
  {
    id: "cake_german_chocolate",
    name: "German Chocolate Cake",
    price: "Rs. 1000",
    discountedPrice: "Rs. 800",
    discount: "20%",
    qty: 1,
    image: German1,
    flavour: "Chocolate",
    bestSeller: false,
    eggless: false,
    weight: "1 kg",
    delivery: "9 January 2023",
  },
];

export let addressBook = [
  {
    id: "add_01",
    title: "Home - Kolkata",
    name: "Baishali Datta",
    phone: "9874723102",
    pincode: "700056",
    address: "8/1 M.B.Road",
    locality: "Belgharia",
    city: "Kolkata",
    state: "West Bengal",
    type: "home",
  },
  {
    id: "add_02",
    title: "Office - Gurgaon",
    name: "Baishali Datta",
    phone: "9830127521",
    pincode: "122008",
    address: "Plot 242-243, AIHP Palms",
    locality: "Udyog Vihar, Sector 18",
    city: "Gurgaon",
    state: "Haryana",
    type: "work",
  },
  {
    id: "add_03",
    title: "Home - Gurgaon",
    name: "Baishali Datta",
    phone: "9874723102",
    pincode: "122017",
    address: "1st floor, 2807",
    locality: "Sector 23",
    city: "Gurgaon",
    state: "Haryana",
    type: "home",
  },
];
